[package]
name = "f-enet-sys"
version = "0.1.0"
edition = "2024"

license = "MIT"
description = "Rust bindings for the ENet networking library"

links = "enet"
build = "build.rs"

[build-dependencies]
bindgen = "0.72.0"
cmake = "0.1.54"
